spring:
  datasource:
    username: wgpark
    password: 123
    url: jdbc:mysql://localhost/chiking
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true